.TH DPKG.RB 1 "Debian Utilities" "DEBIAN" \" -*- nroff -*-
.SH NAME
dpkg.rb \- Utility to read a dpkg style db file, dpkg like program
.SH SYNOPSIS
\fBdpkg.rb\fP [\fB(-l|--list)\fP [\fIpackage\fP ...]] 
.br
\fBdpkg.rb\fP [\fB(-s|--status)\fP [\fIpackage\fP ...]]
.br
\fBdpkg.rb\fP [\fB--get-selections\fP [\fIpackage\fP ...]]
.br
\fBdpkg.rb\fP [\fB--print-avail\fP [\fIpackage\fP ...]]
.br
\fBdpkg.rb\fP [\fB(-L|--listfiles)\fP [\fIpackage\fP ...]]
.br
\fBdpkg.rb\fP [\fB(-S|--search)\fP [\fIpattern\fP ...]]
.br
\fBdpkg.rb\fP [\fB--help\fP]
.br
.SH DESCRIPTION
.I dpkg.rb
parses a dpkg status file(or other similarly formated file) and
outputs the resulting records like 
.I dpkg(1).
.SH OPTIONS
.TP
.PD 0
.BI -l " [package...]"
.TP
.BI --list " [package...]"
.PD
List \fIpackage\fPs.
.TP
.PD 0
.BI -s " [package...]"
.TP
.BI --status " [package...]"
.PD
show status of \fIpackage\fPs.
.TP
.PD 0
.BI --get-selections " [package...]"
.PD
get selections of \fIpackage\fPs.
.TP
.PD 0
.BI --print-avail " [package...]"
.PD
print available of \fIpackage\fPs.
.TP
.PD 0
.BI -L " [package...]"
.TP
.BI --listfiles " [package...]"
.PD
list files in \fIpackage\fPs.
.TP
.PD 0
.BI -S " [pattern...]"
.TP
.BI --search " [pattern...]"
.PD
search package containing files matched \fIpattern\fPs.
.TP
.PD 0
.BI -h
.TP
.BI --help
.PD
Display some help.
.SH BUGS

Be warned that the author has only a shallow understanding of the 
dpkg packaging system, so there are probably tons of bugs in this
program.

This program comes with no warranties.  If running this program
causes fire and brimstone to rain down upon the earth, you will be
on our own.

This program accesses the dpkg database directly in places, querying 
for data that cannot be gotten via dpkg.

.SH AUTHOR
Fumitoshi UKAI <ukai@debian.or.jp>.



